// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeckillMicroService.Context;

namespace SeckillMicroService.Migrations
{
    [DbContext(typeof(SeckillContext))]
    partial class SeckillContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeckillMicroService.Models.Seckill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SeckillDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeckillIsEnd")
                        .HasColumnType("int");

                    b.Property<int>("SeckillLimit")
                        .HasColumnType("int");

                    b.Property<string>("SeckillName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeckillPercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SeckillPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeckillStatus")
                        .HasColumnType("int");

                    b.Property<int>("SeckillStock")
                        .HasColumnType("int");

                    b.Property<int>("SeckillType")
                        .HasColumnType("int");

                    b.Property<string>("SeckillUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seckills");
                });

            modelBuilder.Entity("SeckillMicroService.Models.SeckillRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Createtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderSn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("RecordTotalprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeckillId")
                        .HasColumnType("int");

                    b.Property<int>("SeckillNum")
                        .HasColumnType("int");

                    b.Property<decimal>("SeckillPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SeckillRecords");
                });

            modelBuilder.Entity("SeckillMicroService.Models.SeckillTimeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SeckillDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeckillEndtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeckillStarttime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeStatus")
                        .HasColumnType("int");

                    b.Property<string>("TimeTitleUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SeckillTimeModels");
                });
#pragma warning restore 612, 618
        }
    }
}
